### ISSUE TITLE
tripled_64 is crashing when setting user defined bittiming

### ISSUE THREAD

**Issue by martin-vitek** [canlab-cz/triple#6]
`tripled_64` is crashing when setting user defined bittiming.

```
sudo ./tripled_64 ttyACM0 -s0x09:0x0A:0x21 -c10:6:1:1:10:6:1:1:0:0:2 -ncan0:can1:canfd2
Neoprávněný přístup do paměti (SIGSEGV)
```

With debugging prints:

```
sudo ./tripled_64 ttyACM0 -s0x09:0x0A:0x21 -c10:6:1:1:10:6:1:1:0:0:0 -ncan0:can1:canfd2
str=10, num=10
str=6, num=6
str=1, num=1
str=1, num=1
Neoprávněný přístup do paměti (SIGSEGV)
```

First problem is, that `user_speed` should have 11 items, not only 10:
https://github.com/canlab-cz/triple/blob/4aa706b4d781591f73f6fb49c9082a3e6e77dafc/utility/main.c#L91

Second problem is with `tmp`, which should also have 11 items:

https://github.com/canlab-cz/triple/blob/4aa706b4d781591f73f6fb49c9082a3e6e77dafc/utility/main.c#L107

Both are used in this loop:

https://github.com/canlab-cz/triple/blob/4aa706b4d781591f73f6fb49c9082a3e6e77dafc/utility/main.c#L166-L167

**Comment by canlab-cz** [comment]
Lots of parameters.... I've not tested used user-defined settings, so I'll look into it.

**Comment by canlab-cz** [comment]
Closing
