### ISSUE TITLE
tripled_64: Add predefined CAN FD speeds 

### ISSUE THREAD

**Issue by martin-vitek** [canlab-cz/triple#7]
I'm missing predefined speeds with equal nominal and data baud rates. Would it be possible to add them?

Currently I'm setting 500/500 kb/s with `-c10:6:1:1:10:6:1:1:0:0:0`, is it correct?

**Comment by canlab-cz** [comment]
Sorry, but no, the same speeds are not supported by the firmware as predefined values , mainly because FD CAN is about sending the message payload faster than the rest of the message, having it the same removes one of the main advantages.
